# VM's user and password
eos_default_login: "admin"
eos_default_password: "123456"
eos_login: "admin"
eos_password: "123456"
eos_root_user: "root"
eos_root_password: "123456"

sonic_login: "admin"
sonic_default_passwords:
 - "asteros"
 - "asteros"
sonic_password: "asteros"

k8s_master_login: "ubuntu"
k8s_master_password: "use_own_value"

ptf_host_user: root
ptf_host_pass: root
